test_average (__main__.TestExercice) ... ERROR
test_square (__main__.TestExercice) ... ERROR
test_square_root (__main__.TestExercice) ... ok
test_to_celsius (__main__.TestExercice) ... FAIL
test_to_degrees (__main__.TestExercice) ... ERROR
test_to_farenheit (__main__.TestExercice) ... FAIL
test_to_radians (__main__.TestExercice) ... ERROR

======================================================================
ERROR: test_average (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 44, in test_average
    output = [exercice.average(*v) for v in values]
  File "test_exercice.py", line 44, in <listcomp>
    output = [exercice.average(*v) for v in values]
  File "/home/runner/work/2021h-ch3-exercices-Melvice/2021h-ch3-exercices-Melvice/exercice.py", line 16, in average
    return average (a+b+c)
TypeError: average() missing 2 required positional arguments: 'b' and 'c'

======================================================================
ERROR: test_square (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 28, in test_square
    output = [exercice.square(v) for v in values]
  File "test_exercice.py", line 28, in <listcomp>
    output = [exercice.square(v) for v in values]
  File "/home/runner/work/2021h-ch3-exercices-Melvice/2021h-ch3-exercices-Melvice/exercice.py", line 12, in square
    return square(a)
  File "/home/runner/work/2021h-ch3-exercices-Melvice/2021h-ch3-exercices-Melvice/exercice.py", line 12, in square
    return square(a)
  File "/home/runner/work/2021h-ch3-exercices-Melvice/2021h-ch3-exercices-Melvice/exercice.py", line 12, in square
    return square(a)
  [Previous line repeated 972 more times]
RecursionError: maximum recursion depth exceeded

======================================================================
ERROR: test_to_degrees (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 80, in test_to_degrees
    output = [exercice.to_degrees(v) for v in values]
  File "test_exercice.py", line 80, in <listcomp>
    output = [exercice.to_degrees(v) for v in values]
  File "/home/runner/work/2021h-ch3-exercices-Melvice/2021h-ch3-exercices-Melvice/exercice.py", line 24, in to_degrees
    return to_degrees(angle_rads)
  File "/home/runner/work/2021h-ch3-exercices-Melvice/2021h-ch3-exercices-Melvice/exercice.py", line 24, in to_degrees
    return to_degrees(angle_rads)
  File "/home/runner/work/2021h-ch3-exercices-Melvice/2021h-ch3-exercices-Melvice/exercice.py", line 24, in to_degrees
    return to_degrees(angle_rads)
  [Previous line repeated 972 more times]
RecursionError: maximum recursion depth exceeded

======================================================================
ERROR: test_to_radians (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 61, in test_to_radians
    output = [exercice.to_radians(*v) for v in values]
  File "test_exercice.py", line 61, in <listcomp>
    output = [exercice.to_radians(*v) for v in values]
  File "/home/runner/work/2021h-ch3-exercices-Melvice/2021h-ch3-exercices-Melvice/exercice.py", line 20, in to_radians
    return to_radians(angle_degs, angle_mins, angle_secs)
  File "/home/runner/work/2021h-ch3-exercices-Melvice/2021h-ch3-exercices-Melvice/exercice.py", line 20, in to_radians
    return to_radians(angle_degs, angle_mins, angle_secs)
  File "/home/runner/work/2021h-ch3-exercices-Melvice/2021h-ch3-exercices-Melvice/exercice.py", line 20, in to_radians
    return to_radians(angle_degs, angle_mins, angle_secs)
  [Previous line repeated 971 more times]
RecursionError: maximum recursion depth exceeded

======================================================================
FAIL: test_to_celsius (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 98, in test_to_celsius
    'Mauvais calcul de farenheit -> celsius'
AssertionError: Lists differ: [0.0, 0.0, 0.0] != [-17.77777777777778, -31.666666666666664, 232.77777777777777]

First differing element 0:
0.0
-17.77777777777778

- [0.0, 0.0, 0.0]
+ [-17.77777777777778, -31.666666666666664, 232.77777777777777] : Mauvais calcul de farenheit -> celsius

======================================================================
FAIL: test_to_farenheit (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 110, in test_to_farenheit
    'Mauvais calcul de celsius -> farenheit'
AssertionError: Lists differ: [0.0, 0.0, 0.0] != [32.0, -13.0, 843.8000000000001]

First differing element 0:
0.0
32.0

- [0.0, 0.0, 0.0]
+ [32.0, -13.0, 843.8000000000001] : Mauvais calcul de celsius -> farenheit

----------------------------------------------------------------------
Ran 7 tests in 0.008s

FAILED (failures=2, errors=4)
