test_average (__main__.TestExercice) ... FAIL
test_square (__main__.TestExercice) ... ok
test_square_root (__main__.TestExercice) ... ok
test_to_celsius (__main__.TestExercice) ... FAIL
test_to_degrees (__main__.TestExercice) ... FAIL
test_to_farenheit (__main__.TestExercice) ... FAIL
test_to_radians (__main__.TestExercice) ... ERROR

======================================================================
ERROR: test_to_radians (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 61, in test_to_radians
    output = [exercice.to_radians(*v) for v in values]
  File "test_exercice.py", line 61, in <listcomp>
    output = [exercice.to_radians(*v) for v in values]
  File "/home/runner/work/2021h-ch3-exercices-Melvice/2021h-ch3-exercices-Melvice/exercice.py", line 20, in to_radians
    return (angle_degs*(pi/180 ), angle_mins*(pi/180 ),angle_secs*(math.pi/180 ))
NameError: name 'pi' is not defined

======================================================================
FAIL: test_average (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 50, in test_average
    'Mauvais calcul de la moyenne'
AssertionError: Lists differ: [8.0, -0.6666666666666667, -4.333333333333333] != [4.0, 0.0, -2.3333333333333335]

First differing element 0:
8.0
4.0

- [8.0, -0.6666666666666667, -4.333333333333333]
+ [4.0, 0.0, -2.3333333333333335] : Mauvais calcul de la moyenne

======================================================================
FAIL: test_to_celsius (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 98, in test_to_celsius
    'Mauvais calcul de farenheit -> celsius'
AssertionError: Lists differ: [0.0, 0.0, 0.0] != [-17.77777777777778, -31.666666666666664, 232.77777777777777]

First differing element 0:
0.0
-17.77777777777778

- [0.0, 0.0, 0.0]
+ [-17.77777777777778, -31.666666666666664, 232.77777777777777] : Mauvais calcul de farenheit -> celsius

======================================================================
FAIL: test_to_degrees (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 86, in test_to_degrees
    'Mauvais calcul de radians -> degres'
AssertionError: Lists differ: [114.59155902616465, -229.1831180523293, 2[31 chars]5067] != [(79.0980174562859, 5.881047377154118, 29.[198 chars]998)]

First differing element 0:
114.59155902616465
(79.0980174562859, 5.881047377154118, 29.612494192724625)

- [114.59155902616465, -229.1831180523293, 286.4788975654116, 234.3397382085067]
+ [(79.0980174562859, 5.881047377154118, 29.612494192724625),
+  (-278.1960349125718, 48.23790524569176, 0.7750116145507491),
+  (257.74504364071475, -15.297381557114704, 44.031235481811564),
+  (213.95544569810457, -2.673258113725865, 23.057550624127998)] : Mauvais calcul de radians -> degres

======================================================================
FAIL: test_to_farenheit (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 110, in test_to_farenheit
    'Mauvais calcul de celsius -> farenheit'
AssertionError: Lists differ: [0.0, 0.0, 0.0] != [32.0, -13.0, 843.8000000000001]

First differing element 0:
0.0
32.0

- [0.0, 0.0, 0.0]
+ [32.0, -13.0, 843.8000000000001] : Mauvais calcul de celsius -> farenheit

----------------------------------------------------------------------
Ran 7 tests in 0.003s

FAILED (failures=4, errors=1)
